---
title: |
  As interrelações da pintura, da música e da literatura no período barroco
author: "Leo Gilson Ribeiro"
citation:
  issued: "2022"
  editor: "Fernando Rey Puente"
  original-publisher: "Texto inédito proferido na Escola de Teatro da Universidade da Bahia"
  original-date: "Julho de 1959"
  URL: https://www.leogilsonribeiro.com.br/volume-9/03-as-interrelacoes-da-pintura-da-musica-e-da-literatura-no-periodo-barroco/README
view_url: https://www.leogilsonribeiro.com.br/volume-9/03-as-interrelacoes-da-pintura-da-musica-e-da-literatura-no-periodo-barroco/README
status: "Transcrição concluída. Aguardando revisão"
---

Permitam que antes de iniciar algumas considerações sobre os períodos barroco, romântico e expressionista, eu chame a atenção para a oportunidade de se falar na Bahia, que por vocação e por configuração de nada fortuitas congrega, em sua fisionomia interior e no seu aspecto interno as características dessas três concepções da vida e do mundo. Não bastassem as igrejas e toda a esplêndida arquitetura barroca desta cidade funciona a fundação das Academias de Literatos para dar-lhe esse cunho barroco no campo religioso e no campo literário, já a figura de Gregório de Maros, do Brasil colônia, bastaria para criar entre nós esse primeiro traço barroco: a sátira e a galhofa mordazes que, mais tarde, constituiriam uma das qualidades -- negativa ou positiva -- da índole popular brasileira. Como uma das iniciadoras em nosso país do movimento romântico propriamente dito, a Bahia situou o Brasil com Castro Alves, na esfera dos países em que a revolução político-social preconizada pelos românticos assumia um tom simultaneamente épico, poético e de profundas raízes humanas, na reivindicação dos direitos básicos do ser humano simbolizados pela abolição da escravidão. Não será também uma forma de romantização da vida esse culto baiano pelas festas, pela *féerie* de luzes e cores, em suma: por uma doce e indolente poetização da vida diária? E finalmente, na época atual, em que há pouco cessaram as vozes mestras do expressionismo nessa polifonia de vida social e pesquisa do inconsciente humano que constitui grande parte do Expressionismo e das mensagens vibrantes de Kafka e de Brecht, nesta época conturbada por revoluções tecnológicas radicais e por embates violentos de ideologias políticas e econômicas, não representa também a Bahia, como síntese de todo um regime e de toda uma civilização, aquele lado da vida que Bertold Brecht definiu o lado escuro, que não se vê? Não está representada também nesta cidade, com em todas as outras de todo o mundo, a miséria, os aspectos grotescos do homem já quase identificado com as pedras e com os animais com que convive intimamente, não vemos a cada passo vestígios concretos da injustiça social e do choque de núcleos sociais que constituíram o cerne do teatro brechtiano? Um teatro que, sem dúvida, sofreu a deformação artística imposta por um regime, por uma linha de conduta rígida e doutrinária, mas que, apesar disso, tocou com intuição certeira o âmago da chaga que envenena a nossa estrutura social? Quis-me parecer, portanto, sumamente oportuno, como disse, focalizar alguns aspectos desses três movimentos nesta cidade que recobra novas glórias hoje em dia ao enriquecer o seu patrimônio cultural e com isso o de todo o Brasil de forças vivas de uma cultura eclética e refinada, expressas nos vários campos da música, do teatro e da especulação artística e filosófica. Que esta seja, portanto, também a minha homenagem sincera a este Brasil inicial e contemporâneo, sintetizado na Bahia e no seu renascimento cultural de agora.

Ao observarmos algumas características dos três períodos mencionados, nós centralizaremos a nossa pesquisa em torno da Espanha e da Alemanha, no barroco, da Alemanha e da Inglaterra, no romantismo e na Alemanha e na França, no expressionismo. A razão de tomarmos a Alemanha como ilustração dessas três escolas, se assim as podemos chamar, se prende, primariamente, ao fato de ser esse o único país em que as três formas de expressão artística são, ao mesmo tempo, três grandes fases da cultura nacional. O romantismo e o expressionismo são, de fato, as mais altas e duradouras afirmações culturais autônomas do espírito criador alemão e o período barroco, introduzido da Espanha, marca a eclosão da primeira consciência nacional alemã e a criação de suas primeiras obras-primas no terreno literário e arquitetônico, como veremos mais tarde. Por outro lado, a Alemanha tem assumido, nos últimos cem anos, frequentemente, uma posição de liderança artístico-cultural que justifica plenamente uma difusão mais ampla, entre nós, da sua cultura e dos valores de verdade e beleza que os poetas e pensadores alemães formularam para que eles nos permitam uma visão mais clara da condição do homem sobre a terra.

Depois do Renascimento italiano e do humanismo pan-europeu que colocou o Homem numa posição já reivindicada para ele pela tragédia e pela filosofia gregas -- isto é: a de centro e medida de todo o universo - , a civilização europeia sofreu um impacto múltiplo resultante dessa busca intelectual e idealista de verdades eternas, de arquétipos da cultura ocidental, gravados nas obras filosóficas e literárias da Hélade, transpostas em termo modernos para o terreno da arquitetura, da ética, da política e da erudição. As ideias platônicas do Belo, do Verdadeiro e da imaterialidade do Amor germinaram no culto puramente ideal da Mulher que, como sucedera no período da lírica provençal, passara a simbolizar uma figura de transição entre a divindade e o homem. Mais ainda: uma soma abstrata de valores puramente espirituais, em que a própria Beleza física, como a Beatriz de Dante, inacessível ao toque humano e à vibração da carne, nada mais era senão um reflexo sensorialmente perceptível de Verdades divinas temporariamente enfeixadas num sorriso fugidio, numa cor esplêndida avivada pelo sol, hieróglifos de uma Beleza invisível aos olhos humanos e indecifrável para a nossa limitada concepção mortal. Simbolizada pela descoberta e conquista das Américas, extraordinária amplificação do mundo, as viagens de circum-navegação, o embate das frotas inglesas e espanholas denotavam outra face do Renascimento: o seu elemento real e vivo, a sua realidade dinâmica, em contraposição violenta à busca renascentista de uma contemplação estática, "clássica", por assim dizer, do mundo, em que a mente humana entrava em colóquio com ideias e valores puramente intelectuais e hierárquicos. A Imprensa, com a sua democratização do saber e, acima de tudo, a Reforma, com a sua consequente cisão sanguinolenta do continente europeu em dois campos de batalha ideológica, muitas vezes dilacerando um país em dois, como foi o caso da Alemanha, além de abalar a unidade medieval da Igreja, criou o conceito novo de nação que hoje aceitamos como a manifestação nacional de uma identidade de sensibilidade e de propósitos de um povo. Rompendo a rígida hierarquia aristocrática da exegese religiosa a Reforma permitiu a cada protestante ser o juiz de suas próprias ações, através do código severo que as doutrinas da Bíblia instituíam para o comportamento ético do homem para com os seus semelhantes e o diálogo direto que se estabelecia agora entre o Homem e Deus, o seu Criador, sem intermediários humanos, diretamente de Filho a Pai. É-nos necessária essa sumária caracterização da situação histórica do Renascimento a fim de melhor por em evidência o contraste violento que o Barroco veio estabelecer com essa época precedente. É bastante divulgada a teoria, válida na essência, mas passível de infinitas mutações formais, segundo a qual as correntes artísticas possuem um ritmo próprio, uma sístole e diástole que alternadamente impelem o artista ao mundo que se convencionou chamar de real, para em seguida exercerem sobre ele um movimento inverso, de repulsa e de fuga da realidade ambiental. Ora, traço inconfundível do período barroco -- essa conciliação de extremos, essa coexistência de antíteses -- o paradoxo afirma-se como a determinante essencial da psique barroca. Devemos encontrar na Espanha, matriz incontestável do barroco, as raízes profundas dessa ambivalência talvez única na história de um grande povo. Realmente, não sei de outra grande cultura que consiga, de maneira genial e absurda, conciliar o inconciliável e fazer persistir, paralelamente, a Beleza e o Grotesco, o Sublime e o Sórdido, o Hediondo e o inefavelmente Espiritual, a explosão erótica mais violenta e a transcendência abstrata dos próprios sentidos. Depois da titânica e exaustiva tarefa da colonização da América Espanhola, da imposição às culturas inca, asteca e maia, do dogma do Credo Ortodoxo Católico, a Espanha, batida nos mares pela esquadra de Elizabeth e incapaz, como dizia um cronista da época, de "sorver tantos mares e surpreendida por ver tantas terras sob o seu jugo" passou a militar sob a liderança jesuítica, na reconquista das fortalezas perdidas à Santa Fé Católica pelos heréticos germânicos. Havia novos mundos a conquistar, depois da conquista deslumbrante dos místicos renascentistas, depois da descoberta dos Castelos Interiores da Alma por Santa Teresa, da animação ímpar da Poesia com o sopro da divindade, revelada nas poesias de San Juan de la Cruz: a nova tarefa que se impunha no momento era a de combater o infiéis, não mais os mouros, mas agora os que protestavam contra o luxo voluptuoso do Papado romano, contra os ascetas do Norte que pretendiam destruir o mundo pagão que vira na Corte de Leão X, circundado dos maiores artistas da época, e sufocar aquele que, retomando as amargas críticas de Savonarola, mereciam, como ele, o ferro e o fogo dos defensores da Fé Católica e infalível. É lícito, portanto, ver no barroco, inicialmente, o primeiro veículo, na era moderna, da catequização religiosa e da doutrina católica especificadamente. Na Espanha, onde iremos buscar as origens do barroco, esboça-se com este movimento uma atitude que mais tarde, acentuada pelo romantismo, determinaria a profunda incompreensão do artista hodierno pelas massas. Refiro-me ao isolamento do poeta, notadamente, que assinala o período barroco. Em forte contraposição aos poetas da corte, que mereciam favores reais na França, e dos vates renascentistas, celebrados por elites cultas, senhoras de um estilo poético acadêmico próprio, os poetas e pensadores espanhóis emancipam-se das homenagens tributadas por seus contemporâneos e essa primeira ruptura notamos, acentuadamente, na poesia cujo autor deu o nome a toda essa época -- a poesia gongorista --, como sucedeu com o movimento idêntico na Itália, o Marinismo, que corresponde ao preciosismo francês, ridicularizado por Molière e ao Euphuismo de Lilly, na Inglaterra. As *Soledades* de Góngora, hoje aclamadas como uma das obras-primas da arte moderna, depois da restauração desse poeta levada a cabo por García Lorca, constituem não só o mais válido exemplo da denominada poesia culteranista, isto é: de cunho erudito, aristocrático, como também de obscura formulação e ainda mais complexa interpretação. Pela primeira vez, cronologicamente, na época moderna, cria-se uma poesia subjetiva ao extremo, compreensível, no máximo, a um grupo restrito de iniciados, uma poesia esotérica, reiterada em suas diretrizes ocultas, ao movimento simbolista, por Rimbaud e principalmente Mallarmé. As metáforas audazes empregadas por Góngora foram brilhantemente interpretadas por Damaso Alonso e revelam não só uma vibrante e profunda inspiração poética como uma simbiose de imagens visuais, dinâmicas e auditivas de grande beleza e de grande importância para uma melhor percepção da interrelação dos sentidos no período barroco. É mais especificamente a partir de Góngora que as impressões cromáticas produzem sensações de movimento, que as percepções auditivas adquirem consistência quase visual, ou seja: que a musicalidade corresponde a cores, e som se enlaça à vista e o movimento conduz ao conceito intelectual. As descrições da natureza, neste poema inacabado, situam o homem, isolado -- neste caso um náufrago -- em contato com os aspectos bucólicos da paisagem e com os elementos isolados desta: campos, rios, selva e lugares ermos.

É indispensável, contudo, aludir ainda à explosão dos sentidos, à fúria erótica que se desencadeia com o movimento barroco, uma tentativa ibérica de unir o corpo à alma, de fundir céu e terra num arrebato único de êxtase total. Neste desejo de totalidade, de unidade, vemos a característica mais tipicamente espanhola do barroco, uma característica que se revela constante em toda a sua literatura. Já na extraordinária *La Celestina* medieval, uma das obras de maior vigor da literatura escrita em espanhol, os personagens centrais, no seu desejo mútuo de fusão carnal projetam nesse seu sonho de amor todas as suas aspirações emocionais, todo o seu mundo de conceitos intelectuais e até mesmo de ânsia mística de união com o todo, com esse Deus que o espanhol anela e que procura na amada, nos céus indevassáveis, na ação transformadora da realidade física e na morte, como umbral de uma reunião com o Deus de que se separara a contragosto.

Teixeira de Pascoais, o grande poeta contemporâneo português, viu na civilização ibérica a manifestação "anti-helênica", afirmando que, ao contrário da Grécia, a Península Ibérica cultivava não o Belo, mas o Anti-Estético por excelência. Esta observação assinala, porém, somente parte da verdade, porque, como cita Diaz-Plaja, já o poeta barroco Juan de Cancer exprimira a certeza de que "também no horrível há formosura".

Outra manifestação dessa constante encontramos nos desenhos de Goya, nas suas *brujas y duendes*, no seu realismo cru e franco, em que toda a animalidade do homem é ressaltada voluntariamente, realismo que se une a um tom de revolta social e de ácida ironia dirigida à hipocrisia, à ignorância, à intolerância, à desmesurada ambição e crueldade do homem com o homem. Uma confirmação literária dessa mesma atitude encontramos, principalmente, na "novela picaresca", uma das supremas criações espanholas, levada a grande esplendor literário por Quevedo, o autor barroco da novel do *Buscón*. No entanto, a suprema criação da novela picaresca foi o relato patético de aventuras de *Lazarillo de Tormes*, de autor anônimo. O pícaro, é definido como um personagem esperto, que despreza as leis e vive de sua astúcia, sobrevivendo a uma sociedade inclemente e desumana e passando de amo a amo, através de uma série de peripécias e infortúnios grotescos e trágicos, retratados de maneira caricata pelo autor. O Lazarillo, nascido de pais refratários a qualquer tipo de trabalho honesto, foi entregue por sua mãe, que tinha reputação de bruxa, a um cego caminhante para que a este servisse de guia. Este cego caminhante serviu de verdadeiro mestre a Lazarillo, sendo-lhe mais tarde muito úteis os seus conselhos para que ele se defendesse, com a astúcia, das velhacarias e artimanhas dos seus senhores. O problema central da vida de Lázaro é a fome constante, que o persegue sem cessar, e como solucioná-la. Reconhecendo inúteis os seus esforços de roubar comida a seu amo, Lazarillo se vinga conduzindo o cego avarento de encontro a um poste, num dia de chuva e deixando-o à mingua num descampado. Seu segundo senhor foi um padre guloso e também sumamente avarento, ao qual Lazarillo conseguia subtrair alimentos, retirando-os à noite da arca em que o religioso os guardava sob sete chaves. A princípio ele fazia crer que eram os ratos que devoravam as suas ricas provisões e mais tarde, em vista das ratoeiras mostrarem-se incapazes de pegar ratos, convencendo-o de que era uma cobra que furtava o padre, cujas preocupações eram exclusivamente materiais. Numa cena muito divertida, em que Lazarillo dorme com o apito na boca, apito que ele utilizava para imitar os silvos da cobra e com isso enganar o seu patrão, este se aproxima da cama de Lazarillo e lhe descarrega violentas pauladas, descobrindo-se assim o truque engenhoso do pobre criado. Seu próximo amo tampouco foi mais pródigo: um fidalgo arruinado e sumamente vaidoso, para o qual Lazarillo tinha de obter alimentos sem ferir a sua vaidade. Depois de mil episódios tragicômicos, Lazarillo consegue um ofício real, arauto de Toledo, e se casa com uma criada provida de dote generoso, o que resolve, finalmente, o seu problema fundamental: a fome e lhe traz uma forma de estabilidade, depois de tantas vicissitudes.

A forma da novela picaresca aqui mencionada não é uma criação do barroco em si, mas foi retomada nessa época por Mateo Alemán no seu *Guzmán de Alfarache* e pelo próprio Quevedo no seu *Buscón*. No entanto, as diferenças de estilo e as diferenças da caracterização do personagem central nos três pícaros, o renascentista Lazarillo e os dois barrocos é bastante acentuada. Ao passo que no *Lazarillo* predomina uma nota humorística e quase uma reconciliação bonachona com o mundo das trapaças e da manha que oculta , na realidade, um outro mundo de profunda miséria moral e inflexibilidade de classes sociais estratificadas, nas novelas picarescas do período barroco essa tragédia velada assume notas mais desesperadas e a crítica social, apenas esboçada e levemente irônica no *Lazarillo*, torna-se mordaz e contundente. O Guzmán é um jovem que se move em círculos sociais muito mais elevados que o seu companheiro renascentista: ele serve não a cegos mendicantes e a clérigos de aldeia, mas a um cardeal, ao embaixador da França em Roma, as suas viagens o conduzem fora da Espanha e a sua profunda experiência da vida o induz, velhacamente, a tornar-se padre, a fim de explorar ao máximo a imbecilidade alheia, como ele declara. Os seus furtos, porém, são demasiado escandalosos e ele termina os seus dias na prisão. Como vemos, não a solução de uma necessidade imediata e elementar, como a fome, constitui o móvel das suas ações, mas o desejo de glória, a sua ambição desmedida de dinheiro e de poder. Guzmán possui mesmo certos traços de hipocrisia utilizada com alarde e oportunidade, ao defender a pátria, a religião e fingir enfurecer-se contra as injustiças humanas, sem nada da ingenuidade rude de Lazarillo.

*El Buscón* de Quevedo leva a novela picaresca a seu ápice como descrição hiperbólica e sumamente barroca de fatos e personagens. O livro pode considerar-se realmente uma galeria de caricaturas monstruosas, em que uma nota extremamente amarga de crítica à maldade e ao egoísmo humano faz-se sentir a cada passo. Certas figuras lembram aparições hediondas do pintor flamengo Bosch, em que uma humanidade desfigurada por um materialismo bestial se assemelha já, na aparência física, a animais e bruxos, fantasmas e mistos de fantasia e hediondez. No final da novela, o Buscón, exausto de peregrinar pelas terras da Espanha, embarca num navio que o conduzirá à Índia, lançando impropérios contra a ingrata gente de seu próprio país.

Este desfecho é simbólico para o período culminante do período barroco, principalmente como indicação da atitude do próprio Quevedo. O autor que evocara, em tom elegíaco, a passada e viril glória da Espanha em seu famoso e belíssimo soneto "*ó altos muros de España*" denota aqui, na prosa, o desalento e o desencanto que dele se apossaram com relação à situação presente do seu país. O declínio político da Espanha e a sua sucessiva fuga da realidade europeia de nações -- marcam, melancolicamente, a frase inicial desta época de introspecção ibérica, em que o Império espanhol "no qual o sol nunca se punha" assiste, pela primeira vez, à sua lenta desintegração e ao seu pálido ocaso.

A última voz que se eleva no terreno literário espanhol, além de Góngora e Quevedo é a de Calderón de la Barca, figura representativa do século XVII no teatro castelhano. Em tudo diverso de Lope da Veja, Calderón distingue-se pela sua serenidade e pelo seu retraimento. Sem o forte elemento popular que une Lope às massas da população espanhola, Calderón apesar de sua relativa popularidade excele realmente nos dramas interiorizados, em que se manifesta agudamente o seu desengano pelas coisas da vida e em que a sua estoica e melancólica filosofia conduz as tramas humanas de suas tragédias. Sua religiosidade, mais tarde confirmada por sua ordenação tardia, não o impede de analisar com ceticismo sereno e desiludido o mundo das cegas paixões humanas. Na impossibilidade de mencionar várias de suas inúmeras obras, assinalaremos rapidamente uma de suas "comédias de santos", como elas costuma ser designadas na terminologia espanhola, intitulada *El Mágico Prodigioso*. Esta obra, insuficientemente conhecida do público leitor, constitui uma réplica espanhola à lenda de Fausto, imortalizada por Marlowe no seu fragmento teatral e por Goethe na literatura universal. À semelhança de Fausto, o personagem principal faz um pacto com o diabo, tornando-se senhor de poderes sobrenaturais, que lhe permitem conquistar a amada que se revelara até então inacessível às suas súplicas. Ao abraçá-la, finalmente, ele vê, com espanto, a amada evanescendo-se diante de seus olhos e transformando-se num esqueleto, simbólico, da sua morte espiritual e da punição que sofrerá a luxúria, uma vez revelada a inconsistência dos prazeres carnais.

É, contudo, no seu célebre *La Vida es Sueño* que Calderón dá vazão às suas crenças filosóficas, expressas não só pelo contexto da peça como pelos diálogos e monólogos dos personagens centrais. A par de recursos cênicos de grande efeito, toda a arquitetura dessa peça é entranhadamente barroca: os seus personagens erguem-se como antíteses de princípios morais em choque, o Príncipe prisioneiro da torre solitária já não consegue distinguir a realidade do sonho, tudo se funde na neblina baça e indefinida da aparência vã e é unicamente a fragilidade do mundo ilusório dos sentidos que o leva a crer numa vida imperecível, fora do âmbito estreito das falsas formas humanas. Como diz Calderón por meio de Sigismundo, o Príncipe:

"É verdade, pois reprimamos

Esta selvagem condição,

Esta fúria, esta ambição,

Para se alguma vez sonharmos,

O que sem dúvida faremos, já que estamos

Neste mundo singular,

Onde viver em si já é sonhar;

E a experiência me ensina

Que o homem que vive, sonha

O que é, até despertar...

.......................................

Eu sonho que estou aqui,

Sob a carga rude desta prisão,

E sonhei que já me vi

Em estado mais lisonjeiro.

O que é a vida? Um frenesi.

O que é a vida? Uma ilusão,

Uma sombra, uma ficção,

E o maior bem é, na verdade, pequeno

Pois toda a vida é sonho

E os sonhos, são sonhos apenas."

E, finalmente, na sua comédia *O Príncipe Constante*, Calderón escreve, de certa maneira, o epitáfio da Espanha guerreira e gloriosa, colonizadora de continentes e de almas e encerra o período barroco de seu país com este magnífico soneto:

"Estas que foram pompa e alegria,

Despertando ao alvor da aurora

De tarde serão lamento perdido

Dormindo nos braços da noite fria.

Este matiz que o próprio céu desafia,

Iris listado de ouro, neve e granizo

Será resquício da humana vida:

Tanto se empreende ao termo de um dia!

Ao florescer, as rosas madrugaram

E para envelhecer, floresceram:

Berço e sepulcro em um botão acharam.

Assim os homens a sua sorte contemplaram:

Em um dia nasceram e espiraram,

E, uma vez passados, os séculos foram horas apenas."

Na Alemanha, em que o período barroco importado da Espanha apresenta diversas facetas culturais, como a formação das Sociedades de Preservação de Idioma, o Teatro dos Jesuítas, a Escola de Poesia e Mística da Silésia, a imitação dos modelos clássicos e das literaturas neolatinas, esta época se desenrola, porém, em meio à pilhagem, à luta selvagem, ao fogo e ao massacre da terrível Guerra dos Trinta Anos. Séculos mais tarde, Brecht data ao mundo uma visão muito certeira do que foi essa época na história da Alemanha, com a sua peça *A Mãe Coragem*, ambientada a poucos quilómetros do campo de batalha em que quase a metade de todas as nações europeias se digladiavam num choque armado de convicções religiosas. Além da adaptação genial da novela picaresca às letras alemãs, feita por Grimmelshausen, no seu admirável relato das aventuras de Simplicissimus -- que constitui a primeira obra-prima da literatura em prosa alemã --, é natural que esse período conturbado da história alemã se refletisse na sua temática monótona e apocalíptica. Um dos grandes sonetistas e renovadores da lírica alemã, Gryphius, espelha em seu país e em seu idioma, a mesma angústia manifestada por Quevedo e Calderón. O tema da fugacidade da Beleza, da Vaidade eterna que anima as ações humanas, a instabilidade da deusa Fortuna, que caprichosamente distribui riquezas da terra e esparge o terror e a felicidade com a mesma indiferença que assinala o nascimento ou a morte de milhões de seres humanos, passa a constituir um símbolo da incerteza absoluta em que todos vivem, nessa fase vulcânica de um povo em fermentação político religiosa, em que as bases da nova nação são lançadas em meio a terríveis cataclismas.

Não surpreende, portanto, que os poemas de Gryphius, como arauto desta angústia ansiosa, propalem punições terríveis aos que, em vão, buscam os prazeres fictícios da terra:

"As glórias da terra

Serão em breve fumo e cinzas,

Nem uma pedra, nem um rochedo ficará de pé.

O que nos causa deleito inefável,

E que cremos amar para sempre,

Passará, diáfano, como um sonho."

As advertências de Gryphius prendem-se à sua Fé inabalável num Deus onipotente e onisciente, que flagela a vaidade e o cego egoísmo humanos a fim de elevá-los ao conhecimento de verdades imperecíveis e que transcendem a mísera vida humana. Num de seus sonetos mais fortemente impregnados da certeza cristã, ele compara a sua alma a um batel desmantelado pelas tempestades e invoca a sua alma a despertar, abandonando o jugo da dor, da humilhação e do medo e refugiando-se no castelo eternamente iluminado de Cristo, onde a proteção e a paz liberam finalmente a alma humana dos males ligados à vã existência. No seu drama ele preconiza as virtudes protestantes da virtude, do estoicismo e da abstinência, as suas heroínas são mártires que sofrem torturas indescritivelmente sádicas, mas morrem puras, transfiguradas por uma luz interior que as redime. Apesar deste tipo de teatro não ter hoje em dia qualquer aceitação possível e representar unicamente um documento histórico da evolução do teatro europeu, no entanto, a atitude da Alemanha protestante, invadida pela pompa voluptuosa do rito católico merece ser examinada, pois, como vimos, o que mais repugnou o puritanismo, a frugalidade e a integridade moral de Lutero em Roma foi o desvirtuamento da simplicidade sagrada do rito religioso, aliado, no Catolicismo de então, às manifestações mais licenciosas dos sentidos e ao esplendor de uma pintura calidamente sensual, em que as madonas de Rafael, como rosas prontas a serem colhidas, eclodiam nas telas a sua beleza pagã, o seu perfume de carne feminina e mal ocultavam, em posições aparentemente cheias de pudor, a opulência esplêndida de suas formas.

A interiorização do eu individual típica das culturas germânicas conduz os poetas alemães a estabelecer um diálogo consigo mesmos, evitando um contato direto, um diálogo imediato com o mundo exterior. O mesmo sucede até mesmo com os poetas da escola mais católica, a Silésia, limítrofe com a Polônia, e onde as batalhas mais cruentas da Guerra dos Trinta Anos se travaram. Angelus Silesius, um poeta obscuro e animado de uma inabalável fé em um Deus presente em todas as coisas, um Deus concebido de maneira intelectual, como o Deus de Ignácio de Loyola, que se revelava ao santo como "uma roda de fogo", Silesius no seu *O Viajante Querubim* lega, com seus versos abstratos e de difícil interpretação, novos caminhos à mística moderna, assegurando o homem da existência de Deus em seu próprio interior:

"Homem, onde quer que osciles o teu espírito sobre o tempo e o espaço,

Sempre estarás, a cada momento, no seio da eternidade.

Eu próprio sou a eternidade, quando deixo o tempo,

E Deus em mim e eu em Deus reúno".

O encontro alegórico da Alma com Jesus, o seu Noivo, é reiterado por Silesius, o qual, porém, leva este encontro a uma conclusão nova, pois a fusão entre a Alma e Cristo se faz no interior do próprio ser humano. Por meio da abstinência, da renúncia total ao mundo das aparências, o homem deve gradualmente assimilar a essência de Cristo e transformar a sua alma na substância do próprio Deus, de modo que nele se apague o Homem e só restem o poder, a riqueza e a sabedoria infinitas do Criador original.


