---
title: |
  O Barroco e a literatura
author: "Leo Gilson Ribeiro"
citation:
  issued: "2022"
  editor: "Fernando Rey Puente"
  original-publisher: "In: O Universo Mágico do Barroco Brasileiro"
  original-date: "1998"
  URL: https://www.leogilsonribeiro.com.br/volume-9/04-o-barroco-e-a-literatura/README
view_url: https://www.leogilsonribeiro.com.br/volume-9/04-o-barroco-e-a-literatura/README
status: "Transcrição concluída. Aguardando revisão"
---

Catálogo da Exposição - Galeria de Arte do Sesi: 3 de março a 3 de agosto de 1998 (pp.358-361)

O movimento barroco coincide com o início da decadência da Espanha, no século XVI, depois da derrota da chamada *invencible Armada* (em 1588) pelas naus inglesas da Rainha Elizabeth I. A lenda relata que o rei espanhol, desesperado e colérico, teria exclamado: "Não enviei meus navios para lutarem contas os elementos", referindo-se à fúria dos ventos que tanto ajudaram as embarcações da "herege" Inglaterra a conquistar o domínio dos mares. Paradoxalmente, no Brasil, o período barroco foi o do nosso domínio pelo espanhol, já que uma luta dinástica, em torno do trono de Portugal, invadira o Reino e, consequentemente, o Brasil se tornara, durante algumas décadas, colônia da Espanha.

Literalmente, há críticos que colocam obras de menor valor, mas historicamente de século anterior, como "o início" da nossa literatura. Anchieta e seus poemas em português e tupi e suas peças teatrais nada mais eram que obras de catequese dos indígenas, desprovidas de originalidade e qualidade duradoura. Da mesma maneira, há quem considere livros de descrição de viajantes ao Brasil ou a montanha de versos insossos de Bento Teixeira e sua insignificante *Prosopopéia* como as primícias da nossa presença nas letras, de forma independente e inconfundível. Na realidade, o Barroco foi o selo autêntico, novo, do Brasil, mesmo no período colonial do obscurantismo sufocante mais sufocante, pois a imprensa de Gutenberg fora terminantemente proibida na Bahia e no restante da colônia. E o foi nos poemas ricamente variados de Gregório de Matos Guerra, este, sim, o único autor de uma nacionalidade que se esboçava já na literatura, com seus versos fulminantes de sátira, de pornografia, de erotismo ou, no final de sua vida, fulgurantes de misticismo ou de amor cristão. Gregório de Maros Guerra, hoje em dia, se choca com o "politicamente correto" e também com a nova sensibilidade. Esse fauno machista, esse arrogante racista contra os indígenas, os mulatos e os negros, ao contrário, se torna repelente ao condenar as mulheres, os homossexuais e os que não são da raça branca, ao escárnio e ao mais vil desprezo.

Ora, esses preconceitos não invalidam a sua obra. O que afasta principalmente a sua leitura é a dificuldade de decifrarmos o seu opulento vocabulário, em parte obsoleto e que, em muitos e muitos pontos, torna necessário ter à mão, permanentemente, um dicionário, a fim de o compreendermos. Não há necessidade de captarmos a sua ambiguidade com relação à excitação sensual que nele desperta "a crioulinha Francisca", "a mulata Bartola": ela palpita em seus versos de louvor às amantes de qualquer tom de pele imaginável.

Involuntariamente talvez, iniciava-se, de modo paradoxal, a ode a uma população francamente miscigenada, a amálgama que começava então entre o branco, o negro e o indígena, mistura à qual séculos mais tarde seria acrescentada a nuance oriental dos imigrantes japoneses, chineses, coreanos. Biograficamente, o poeta baiano era o que já se designou como "náufrago erudito": homem culto esquecido numa terra ainda bárbara, sob o ponto de vista da instrução primária, quanto mais da cultura! Não é só o sarcasmo ardente que ecoa através do tempo em seus versos tão eloquentes -- a Bahia vista por ele resume-se a um retrato impiedoso e desalentador:

"A cada canto um grande conselheiro,

Que nos quer governar cabana e vinha;

Não sabem governar sua cozinha,

E podem governar o mundo inteiro.

Em cada porta um bem frequente olheiro

Que a vida do vizinho e da vizinha

Pesauisa, escuta, espreita e esquadrinha,

Para o levar à praça e ao terreiro.

Muitos mulatos desavergonhados,

Trazidos pelos pés aos homens nobres,

Posta nas palmas toda a picardia.

Estupendas usuras nos mercados,

Todos os que não furtam, muito pobres;

Eis aqui a cidade da Bahia."

Ou, no terceto final, que descreve a procissão de Cinzas em Pernambuco:

"Atrás um cego, um negro, um mameluco,

Três lotes de rapazes gritadores:

É a procissão de Cinza de Pernambuco".

Por trás da ironia racista, um quadro realista da imemorável miséria brasileira, um quadro social de elites econômicas dominantes em nossa quase imutável pirâmide social: abolida a escravidão racial, não continua, a mesma, a escravidão social?

Espantosamente "moderno" para nossos ouvidos, Gregório de Matos Guerra inaugura um estilo que só depois de 1922, depois de Mário de Andrade e Oswald de Andrade, na revolução modernista de São Paulo, conquistaria tal liberdade e espontaneidade de expressão. Em um de seus numerosos sonetos ousadamente anticlericais, anti-falsos nobres e anti-canalhas ladrões dos indefesos, ele ousa terminar com este linguajar:

"Para a tropa do trapo vazo a tripa

E mais não digo, porque a Musa topa

Em apa, epa, ipa, opa, upa.",

esclarecendo-se a expressão "vazo a tripa" como significando que o poeta defeca em cima da tropa do trapo, ou seja: os baianos que queriam, como certos reinóis vindos do nada, arrotar brasões antigos e imaginários. E sem esquecer que em outro soneto ele reconhece, sim, a nobreza dos que, com traços marcados de indígenas, na verdade têm o seu quê de nobreza, pois os antepassados desses "nobres" de mentira e falso orgulho tinham comido até os ossos dos nobres que sua tribo tinha arrasado em combates mortais.

Não espanta que tanto a corte portuguesa como também a espanhola, vigentes naquela época, transformassem seus versos em um nosso contemporâneo de século: um *samizdat*, aquela literatura vasta e subterrânea da Rússia soviética, na qual as obras de denúncia ao regime passavam, como as de Gregório de Maros Guerra, o "Boca do Inferno", de mão em mão.

Igualmente brasileiro é um estilo que reflete a natureza tropical, completamente diversa da europeia, a nascente diversidade de raças, termos roubados ao tupi-guarani, menções da flora e da fauna brasileiras.

Fiel ao espírito do seu tempo, Gregório de Matos Guerra aconselha todos a gozarem o efêmero da mocidade, o viço da beleza jovem, um *carpe diem*, que a ampulheta do tempo de vida que nos foi concedido esgota o pouco de areia que desce entre os vidros. A vida, o êxtase dos sentidos -- lembra sempre o escritor barroco -- é o momento fugidio, a marca do efêmero de tudo que já viveu ou vive, contraste apavorante com a sepultura, a morte, a volta ao pó de que somos feitos momentaneamente "em cinzas se torna a formosura... em cadáver se muda a fidalguia...". Na literatura brasileira, o Barroco, importado da Espanha de Góngora e de Quevedo, se move sempre entre os extremos, os superlativos, de arrebatamento diante da beleza ou de terror diante do monstruoso e ameaçador: a prisão, a lepra, a miséria, a loucura, a mutilação, a paralisia, a morte.

Como outros grandes autores que passaram do culto de um amor pagão e sem peias para uma sincera conversão à Fé em Deus Todo-Poderoso, também Gregório de Matos Guerra coloca toda a sua derradeira esperança na misericórdia divina, a única capaz de salvar a sua alma pecadora, como o grande poeta inglês John Donne ou o autor barroco alemão Grimmelshausen em sua obra-prima *Simplicissimus*, do século XVII. Antes da prece comovente a Deus para que lhe perdoe os erros em vida e lhe conceda indulto espiritual depois da morte, Gregório de Matos Guerra saúda o Juízo Final como a trombeta triste que marca o fim de tudo:

"O alegre do dia entristecido,

O silêncio da noite perturbado,

O resplendor do sol todo eclipsado,

E o luzente da lia desmentido.

Rompa todo o creado em um gemido,

Que é de ti, mundo? Onde tens parado?

Se tudo neste instante está acabado,

Tanto importa o não ser, como haver sido.

Soa a trombeta da maior altura,

A que vivos e mortos traz o aviso

Da desventura de uns, de outros ventura.

Acabe o mundo, porque já é preciso,

Erga-se o morto, deixe a sepultura,

Por que é chegado o dia do juízo..."

A figura que se contrapõe de todo a Gregório de Matos Guerra e, de certo modo esdrúxulo, o complementa, é o Padre Vieira. Disputado, por ter nascido em Portugal, como autor lusitano, é considerado também brasileiro pelo país ao qual chegou ainda menino e ao qual dedicou sua profícua vida inteira de admirável orador e pensador. As próprias circunstâncias iniciais de sua vida esboçam o seu itinerário literário. Um ano (1623) depois de ter ingressado, muito jovem ainda, como noviço na Companhia de Jesus da Bahia, os jesuítas se veem forçados a refugiar-se no interior, numa aldeia de silvícolas, fugindo dos invasores holandeses que já tinham se apossado da Capital da Bahia. Eis aí, claramente mencionadas, duas teses das várias que assinalarão o Padre Vieira como um defensor dos índios contra seu escravizamento em defesa do que então começava a delinear-se como o Brasil, ainda que de forma balbuciante: é o segundo tema a que ele dará o timbre e a eloquência de sua voz poderosa, superiores os seus sermões, segundo muitos críticos, aos do próprio e famoso orador francês, Bossuet. Ao contrário do poeta, Vieira ama os naturais da terra, percorre longamente suas terras, como missionário, atingindo tribos jamais contatadas por um homem branco nos grotões do Amazonas, do Pará e do Maranhão, com todas as dificuldades de acesso e locomoção típicas da sua época. Mesmo quando, durante um intervalo, volta a Portugal, já se torna estranho aos ouvidos de Lisboa "o sotaque brasileiro do pregador", com uma oratória que pouco a pouco se tornava internacional pelo seu vigor e pelo intrincado de seus pensamentos. De acordo com o poeta, porém, ele estaria, mesmo que insensivelmente, inconscientemente, contribuindo ao crescente "abrasileiramento" do idioma. Todos os recursos de um quase dialeto surgem para distinguir "o falar brasileiro" do "castiço português": termos aborígenes como *igarapé*, *buriti*, *oca*, nomes da terra como *Moema*, *Paraguaçu*, *Caramuru* etc., problemas da terra nova de estradas que faltavam, de apoio sobretudo aos aborígenes, que Padre Vieira compreendia, tragicamente, estarem fadados a desaparecer quase que completamente, vítimas da ganância insaciável dos portugueses e dos brancos brasileiros por suas terras e as colheitas e minerais que elas contivessem. Há, para nós do final do milênio, uma nota franca de defesa das tribos e sua diversidade, de defesa de suas línguas agonizantes, do direito dos homens nascidos nas matas e -- o que soa a algo muito contemporâneo -- a formulação de uma moderníssima ecologia, embora tivesse o nome mais clássico de "preservação das matas e da maneira de viver de nossos irmãos das selvas".

Jamais Vieira teve desavenças com os naturais da ampla colônia, 16 vezes mais vasta do que todo o território do minúsculo Portugal. Não só -- segundo as leis da Companhia fundada por Santo Inácio de Loyola, na Espanha -- aprendera facilmente as diversas línguas das diversas tribos com as quais entrara em contato (não se falava ainda a língua geral, tupi-guarani) como se adentrara também sempre, com valente coerência, em defesa do índio que se queria escravizado no Brasil para enriquecer um punhado de portugueses e de brasileiros ociosos e sequiosos de se tornarem ricos à custa do seu trabalho *grátis*. Para qualquer pessoa sensível, o Padre Vieira cometeu o mesmo erro que o religioso De Las Casas, ao crer, erroneamente, que o gentio se prestava menos ao trabalho servil do que os africanos, erro que hoje concordamos que foi e será de todo imperdoável.

Sobressai logo outro traço de união entre o poeta Gregório de Matos Guerra, galhofeiro, denunciador de goyescas orgias de freiras e frades em conventos comandados pelo Demônio, e o Salvador de Almas para Cristo no mais cerrado da floresta amazônica, quando necessário: ambos, de uma cultura europeia altíssima, dirigiam-se a populações -- mesmo as da Bahia de então -- sumamente incultas, a esmagadora maioria das quais mal sabia ler ou escrever.

No entanto, desde o início da pregação de seus impressionantes sermões pelo Brasil afora, e mais tarde mesmo em Roma, na Itália, o Padre Vieira parte sempre da nota característica do ideário barroco: a vida é um sonho, tudo é efêmero, a inovação heroica procede do estoicismo de Sêneca e de Marco Aurélio: a vida é um sofrimento infindável, que só se detém com a morte. A morte deve ser nossa preparação diária, momento a momento, pois não se sabe quando um de nós pode tombar, flechado pelo veneno de um atirador índio inimigo feroz ou sob o impacto repentino de um infarto do coração, no meio de uma frase para sempre deixada por terminar. O linguajar pode ser aristocrático, o Latim imemorial da Antiga Roma e da liturgia da Igreja, derivada da Bíblia: "*Memento homo, quia pulvis es, et in pulverem reverteris*" ou seja: "Lembra-te, homem, que és pó e em pó hás de te tornar". A morte, no entanto, não assinala o fim de tudo, o esquecimento total de tudo que houve durante uma vida. Ela trará a Balança do Julgamento do Dia Final, quando os bons irão para o céu e os pecadores para o inferno. Antes disso, acentua-se sempre, nos sermões de Vieira, a fragilidade intrínseca do mero viver: Jó, em meio a suas tribulações, proclamava, dolorido, "*qui ventus est vita mea*", "que minha vida é um sopro". Santo Agostinho ia mais longe, em seu intuito de mostrar a falta de lógica em qualquer pompa humana, de monarcas, nobres, plebeus, todos horizontalmente indistinguíveis na sombria "democracia" final da mortandade geral:

"Olha para dentro dos sepulcros e vê: quem é o senhor? quem é o servo? quem é o pobre? quem é o rico? Distingue, se podes, o rei dos vencidos, o forte do fraco, o belo do deformado..." Imperadores, servos, sátrapas, vencedores, vencidos, imperadores insuperáveis em seu poderio, generais de fortíssimos exércitos, tiranos de ontem -- onde jazeis todos agora? De acordo com esse quase "culto da morte", o Barroco desenterra os exemplos contidos na Bíblia, quando a podridão é chamada, por Jó, de seu pai, e os vermes que devorarão seus restos carnais, "minha mãe e minhas irmãs". Não só essa ideia lúgubre do aniquilamento existe: coexiste com ela a noção de libertação dos sofrimentos que a carne e a velhice trazem com o passar inevitável dos anos e a morte nos adverte de que devemos viver sim, mas livres do pecado.

Para nossa sensibilidade deste final de século XX, os diagnósticos certeiros e profundos que Vieira deixou a respeito de o Brasil ser "um enfermo", sem assistência de quaisquer autoridades no atendimento de nossas necessidades básicas -- escola, hospital, moradia, emprego, estradas etc. -- ele tirou um luminoso e ainda válido raio-x ou tomografia dos países pobres que compõem 3/4 da humanidade ainda hoje, imutavelmente.

Como rápido exemplo, o Sermão eloquentíssimo em que ele roga a Deus, quase que com impertinência, que não permita que os holandeses se poderem daquele que será futuramente o Brasil, ele usa de artimanhas soberbamente ditas:

"Mas, pois, vós, Senhor, o quereis e ordenais assim, fazei o que fordes servido. Entregai aos holandeses o Brasil, entregai-lhes as Índias, entregai-lhes a Espanha (que não são menos perigosas que as consequências do Brasil perdido), entregai-lhes quanto temos e possuímos (como já lhes entregastes tanta parte), ponde em suas mãos o Mundo; e a nós, aos portugueses e espanhóis, deixai-nos, repudiai-nos; desfazei-nos, acabai-nos. Mas só digo e lembro a Vossa Majestade, Senhor, que estes mesmos que agora desfavoreceis e lançais de vós, pode ser que os queirais um dia, e que os não tenhais". Mais ainda, aquele trecho de uma eloquência clássica, digna de Quintiliano ou de Cícero, e que tanto impressionou o próprio Ruy Barbosa quando o Padre Vieira lança seu brado aos céus:

"Não hei de pedir pedindo, senão protestando e argumentando, pois esta é a licença, e a liberdade, quem tem, não pede favor, senão justiça". Um refrão que passou a ser a defesa da liberdade em todos os quadrantes.

O Barroco brasileiro, portanto, não se distingue por obras tênues, facilmente esquecíveis como a estulta *Música do Parnaso* de Botelho de Oliveira, nem os toscos *Diálogos das Grandezas do Brasil* deixados por um tal de Ambrósio Fernandes Brandão. Todos são meras imitações canhestras de modelos portugueses renascentistas aos quais se mostram ridicularmente inferiores. O Brasil se afirmou, primeiro, com a sátira contundente e a Fé exultante, em nossa Literatura. Logo depois, viriam os poetas das Academias esquecidas, em Minas e na Bahia, e os mártires da Inconfidência Mineira. Mas desde 1600 o Brasil, com Aleijadinho e sua arquitetura e escultura e uma literatura do alto valor de Gregório de Matos Guerra e do flamejante Padre Vieira, o Brasil respondia pelas três Américas como altíssimo padrão de qualidade e de permanência através dos séculos vindouros.

Discurso feito no lançamento do 1º Concurso Nacional de Contos

Curitiba 1967/11/21

Este concurso inicia-se com uma mescla de alegria pela iniciativa que vem dinamizar a criação literária no Brasil e com a tristeza prematura que enlutou a nossa literatura no último domingo com a morte prematura, sempre prematura, de Guimarães Rosa. Portanto inicialmente eu desejo pedir ao senhor Governador e aos membros da comissão julgadora, que se dê o nome de Prêmio Guimarães Rosa ao prêmio especial que complementa o prêmio Paraná. Pois quem mais especial dentro do conto que o genial autor de *Corpo de Baile*, de *Tutameia*, *Sagarana* e *Primeiras e Terceiras Estórias*? Desta forma, o mais novo e mais estimulante apoio à literatura jovem do Brasil se une à obra do mineiro universal que integrou o Brasil na literatura, no espaço geográfico e no decurso do tempo. Dessa forma nós unimos, o presente e esta iniciativa vibrante, que incide sobre o futuro de nossa literatura, ao seu valor perene, e revolucionário e intemporal ao mesmo tempo, o valor de Guimarães Rosa.

Não pretendo absolutamente fazer um discurso. Se eu fizesse um discurso, deveria ser imediatamente desclassificado da honrosa incumbência que me foi confiada como membro da comissão julgadora do extraordinário certame literário instituído pelo Governo do Estado do Paraná; porque o que nós visamos justamente através desta garimpagem de talentos desconhecidos Brasil a fora é extirpar o conceito retórico do emprego da palavra que entre nós se entrincheirou tradicionalmente na epidemia discursiva nacional, símbolo de um conceito puramente ornamental da faculdade de comunicação do homem.

Eu venho em primeiro lugar -- e estou certo disto -- expressar o sentimento de surpresa e de gratidão, de entusiasmo e esperança que colher a intelectualidade brasileira ao ter notícia da generosidade do mecenato cultural do Paraná. Mas esse agradecimento e esse legítimo júbilo, Senhor Governador, só têm sentido e só adquirem sua proporção devida, quando contrastados com a situação cultural brasileira antes dessa dinâmica e estimulante intervenção do Estado que Vossa Excelência conduz administrativamente.

Qual era e qual é ainda a situação real do intelectual brasileiro e, mais especificamente, do escritor brasileiro na época atual? Em que pontos ele difere ou coincide com a situação em outros países? Examinada nesse contexto, nós chegamos a uma concisa e exata diagnose do *status* do literato ao afirmar que ele se encontra bifurcado entre duas superpotências atômicas e tecnológicas atuais, no mundo separado, além do muro de Berlim, por um muro ideológico e por concepções da economia, das tarefas da coletividade e do Estado, da cultura, e, em última análise, do homem diametralmente opostas. O escritor na era da cultura de massas, da industrialização do produto cultural através da imprensa, do rádio, do cinema, do teatro, das grandes tiragens editoriais, o escritor encontra-se diante de duas possibilidades com pequenas variantes locais que não alteram, porém, a essência dessa férrea bipartição de caminhos que se abrem diante dele. De um lado, tomando os Estados Unidos como exemplo do sistema ocidental capitalista, o escritor tem que se curvar às leis da oferta e da demanda do mercado cultural artificialmente formuladas por uma gigantesca máquina publicitária. Isto é, o escritor tem que produzir de acordo com os critérios de Hollywood e da Broadway, escrever novelas e contos lacrimosos e *sexy*, mas, se possível, com um final feliz, aquele *happy end* sem o qual a saída da mercadoria fica prejudicada. O critério preponderante, o método utilizado no julgamento de valor de um escritor é a venda, o do lucro que o termo *best seller* -- melhor vendagem -- define lapidarmente. O escritor está então submetido ao objetivo comercial da difusão quantitativa de um produto esterilizado, conformista, segundo um conceito puramente digestivo e recreativo da literatura?

E no mundo comunista do Leste, exemplificado pela União Soviética?

Nela o escritor tem que se curvar a um outro conformismo político-cultural. As obras literárias têm que forçosamente seguir os modelos do realismo socialista decalcado dos conceitos puritanos da Rainha Vitória, que continuam vigentes na Rússia de Stalin e de Krucehv, de Brejnev e de Kosiguin. A literatura deve retratar situações sociais segundo o rígido modelo marxista, deve ser uma literatura otimista, que exalta o lado utópico e róseo da sociedade soviética. Qualquer transgressão é paga com o encarceramento ou exílio na Sibéria e trabalhos forçados e com a proibição de publicação de suas obras pelas editoras, pois todas, naturalmente, estão em mãos do Estado. Na China continental a situação parece ainda mais grave e a sanha inquisitorial da guarda vermelha, a qual queima em fogueiras, que sinistramente lembram as fogueiras do nazismo, livros de Shakespeare e sonatas de Beethoven, sinfonias de Mozart e o Dom Quixote de Cervantes.

As poucas variantes que existem constituem a literatura de protesto, vigorosa e ativa tanto nos Estados Unidos onde é formulada livremente nas obras de James Baldwin, de Norman Mailer, das canções de Bob Dilan e Joan Baez. Na Rússia, por meio da literatura de exílio de obras publicadas no ocidente e contrabandeadas clandestinamente do país, como o *Dr. Jivago* de Pasternack, as obras satíricas de Daniel e Siniaveski e as memórias da filha de Stalin, embora, durante o breve período de degelo Evtuchenko em sua autobiografia e Ehrenburg em suas volumosas memórias, tenha denunciado veementemente o terrorismo cultural da era stalinista ao qual Sartre dedica agora uma excelente análise no seu livro denominado o *Fantasma de Stalin*.

Se as condições de sobrevivência do escritor e da sua obra são tão pouco animadoras na parte bem nutrida do mundo, na metade que dispõe da alquimia, da tecnologia e dos computadores para aumentar a riqueza e o bem-estar econômico dos seus povos em nações desenvolvidas -- o que diremos então do escritor no Brasil? Por obra de que indômita teimosia ele consegue não afundar dentro de um contexto econômico, cultural e educacional em que faltam até as premissas, digamos assim biológicas, para que o cérebro e a sensibilidade humanas possam como antenas sensíveis captar a realidade circundante e interpretá-la em termo de literatura? Porque o subdesenvolvimento é uma forma de multiesclerose que ataca todo o organismo vivo de uma coletividade nacional, é uma série de fomes simultâneas e todas urgentes, todas prioritárias, porque todas juntas compõem o ser humano. Setores majoritários da literatura brasileira são, então, sacrificados, triturados, perdidos para o enriquecimento espiritual do Brasil e da Humanidade, devorados num campo de batalha quotidiano e implacável que impede esse enriquecimento, exigindo todas as forças para conter o empobrecimento e a desnutrição. Assim como no Brasil, o grosso do orçamento nacional é absorvido pelos *déficit*, pela sonegação de impostos, pelo pagamento de um funcionalismo numeroso e em grande parte excessivo e parasitário, também no campo da cultura e especificamente da literatura, as energias individuais são malbaratadas no exercício de funções que as desviam da literatura, que são hostis à literatura, que ocupam o lugar que legitimamente deveria caber à literatura. Quais?

Os magros cofres dos governos estaduais e federal passam a ser encarados como uma pensão vitalícia irrisória, é verdade, mas sempre vital para a manutenção física do candidato a escritor no Brasil. As agências de publicidade oferecem-lhe um diversivo também, e muito que potencialmente poderiam expressar-se e expressar o Brasil através da literatura, passam então a criar *jingles* e frases publicitárias que devem fustigar a vaidade do público, incitá-lo a comprar este ou aquele detergente, este ou aquele sal-de-frutas que cure as dispepsias de uma sociedade opulenta minoritária na área centro-sul do país.

Ou o magistério acena com a sua total ausência de qualquer tradição universitária, criadas que foram quase todas as nossas universidades durante a ditadura getulista na década de trinta, e, até hoje totalmente desaparelhadas, tanto com meio de ensino como, sobretudo, como conceito de ensino, representantes de um Brasil arcaico e estático, medieval e verboso defensor de um *status* político, social, econômico, educacional e cultural.

As traduções que poderiam e deveriam constituir uma fonte de renda legítima e compatível com o exercício paralelo da literatura, são menos compensadoras do que a mera cópia datilográfica de apostila de Biologia ou Matemática, pois no Rio e em São Paulo uma datilógrafa, copiando em português um texto, ganha mais por páginas do que um tradutor brasileiro, traduzindo do inglês, do francês, do alemão etc. um texto literário ou de Sociologia, Economia, Política etc. para o português. Mesmo no caso de traduções, que rendem muito -- para o editor -- o tradutor recebe exclusivamente a esmola inicial pela sua dedicação, enquanto os lucros permanecem exclusivamente para o editor, para as livrarias e para os distribuidores.

O jornalismo então -- no Brasil crescentemente divorciado da cultura -- passa a ser o mal menor, a precípua tabela de salvação do escritor, já que naturalmente escrever livros em si significa profissionalmente candidatar-se a faquir, condição a que o postulante a escritor fatalmente arrastará sua família, seus dependentes. Com a possível e única exceção de Jorge Amado, nenhum escritor brasileiro -- do mais excelso ao mais modesto -- pode viver exclusivamente de literatura, sem esquecermos que Jorge Amado dispõe de vultosos lucros derivados da tradução de seus livros em inúmeras traduções estrangeiras.

É esse dividendo estrangeiro talvez que lhe possibilita fugir às outras funções não-literárias a que estão condenados os escritores no Brasil, diplomatas como Guimarães Rosa, colaboradores de jornais e revistas como Clarice Lispector, funcionário hoje aposentado como Carlos Drummond de Andrade, professor universitário como Manoel Bandeira etc. etc.

Porque a questão dos direitos autorais espelha amplamente a precariedade da profissionalização do escritor no Brasil. Copiada da legislação estrangeira, sem nenhuma adaptação ao nosso meio circulante e à nossa taxa de analfabetismo, a nossa lei prevê que o autor receba 10% do preço de venda de cada volume. No entanto, dez por cento de um dólar não equivalem a dez por cento de um cruzeiro, e uma tiragem média de 5 a 10.000 exemplares, que é a comum entre nós, não corresponde a 50.000 exemplares, que é a tiragem mínima de um livro na Alemanha ocidental. Seria inútil alongarmo-nos nessa análise desesperadora da literatura, atividade marginal, ornamental, para ser subtraída às horas de repouso e para ser exercício nas horas vagas num país em que a literatura significa boêmia, negação dos valores utilitaristas de uma sociedade baseada no lucro, no conforto, no prazer, no progresso material; significa caturrice de que prefere enfronhar-se num livro, em vez de prestar sua homenagem no altar doméstico da televisão, queimando incenso diante dos deuses protetores da imbecilização perpetuada, que pululam no Olimpo do nosso vídeo, Chacrinha, o Júpiter surrealista que abandonou o raio por uma buzina, e em vez de transformar-se em touro para raptar Europa ou em águia para raptar Ganimedes, transforma-se de minuto em minuto com roupagens e atavios que ilustram pateticamente o círculo vicioso da manutenção de um povo no nível mais primário possível.

As Casas da Banha patrocinam a imbecilização do povo brasileiro porque acham que ele não quer outra coisa, e o povo brasileiro submete-se a essa narcotização de sua inteligência, porque as Casas da Banha não ousam apresentar-lhe outra coisa menos hedionda.

Mas, e aqui nos aproximamos já do final para não cansar demasiado a paciência dos que cortesmente ouvem esta prestação de contas, este boletim do doente grave, o escritor brasileiro, mas o Brasil não é esse monólito desolador, não é esse muro das lamentações de 8 milhões de quilómetros quadrados.

O Brasil conta na sua simultaneidade das sociedades que se defrontam -- a arcaica e renovadora com uma juventude universitária rebelde ao *status quo*, o Brasil formula também a sua literatura de protesto, o seu cinema novo, a sua música popular plenamente afirmada, o Brasil teve em Juscelino Kubitschek, o seu Pedro o Grande, o Capitalizador e símbolo da vontade brasileira de mudar para não perecer, mudar para viver, para afirmar-se plenamente no citadíssimo concerto das nações no qual até agora só tocávamos os instrumentos desprezados pelos outros musicistas, esquecidos do regente dessa orquestra internacional.

E se Brasília, a cidade da esperança como a chamou André Malraux, se a estrada Belém-Brasília, se Furnas e Três Marias, se a Indústria Naval e a Indústria Automobilística brotaram de engenho e da grandeza desse estadista sem par no Brasil, hoje nós estamos aqui reunidos para celebrar os primeiros sinais de convalescença da literatura brasileira, como renovação de valores, como conquista territorial, como abertura de novas perspectivas para um outro Brasil, mais justo, mais consoante com a sua vocação liberal, mais fiel aos princípios cristãos empoeirados pelo desuso, ao lado de Brasília surge no plano da literatura esta iniciativa do Governo do Paraná, aqui ilustremente representado pelo Dr. Paulo Pimentel. Porque acostumados a uma valoração puramente visual e quantitativa, raramente atentamos para a grandiosidade de uma empresa que não se concretiza numa catedral, numa rodovia, num acender luzes em aldeias que até então viviam na treva medieval da vela de cera, mas é preciso reconhecer que, proporcionalmente, a estrada que o Governo do Paraná inaugura hoje -- assessorado pela Andreazza da cultura paranaense que é a Fundepar -- corresponde à duplicação da via Dutra e à pavimentação da Brasília-Acre. É preciso reconhecer que estes 25 mil cruzeiros novos, vem quebrar vigorosamente, e esperamos com todo o entusiasmo que definitivamente também vem quebrar o círculo vicioso do marasmo literário brasileiro do qual se excluem naturalmente algumas, poucas, figuras de renome justamente internacional. Eu diria que hoje, aqui em Curitiba se faz mais ainda: hoje o Paraná precede à captação dos milhões de kilowatts da Foz do Iguaçu com a captação dos milhões de kilowatts da inteligência e da sensibilidade brasileiras que os prêmios deste concurso nacional de contos irão colocar em benefício da cultura e do progresso social do Brasil.

Não é só de pão que vive o homem, como diz a Bíblia, e como confirma o romance do escritor soviético Dudintsiev, que, com a autoridade da experiência pessoal, denomina de comedores de metal os tecnocratas modernos -- tanto no Ocidente quanto nos países comunistas -- que fornecem ao ser humano apenas uma reestruturação do sem bem-estar, da sua saúde, das sua realidade físico-biológica através da socialização econômica de uma coletividade ara que seus frutos sejam equitativamente distribuídos entre todos os seus integrantes, sem as distorções que ainda reformam os regimes de capital meramente espoliativo, síntese social do egoísmo individual de oligarquias suicidas e divorciadas de qualquer comezinho sentido ético ou cristão.

O Brasil de hoje insiste, com razão, na prioridade da transformação das condições físicas de habitabilidade do nosso país. Dentro de um sadio e vigoroso pragmatismo rasgam-se estradas, renova-se a marinha mercante, domam-se cachoeiras para delas extrair a eletricidade como Prometeu roubando aos deuses do fogo, o engenheiro, o físico, o químico, o matemático, os técnicos imperam e esmagam as Faculdades de Direito, as Faculdades de Filosofia e Letras, o beletrismo nefasto do Brasil arcaico. Mas se antes pecávamos por excesso de advogados dentro duma sociedade, necessitando de médicos, agrônomos, engenheiros e físicos, hoje pecamos por excessiva ênfase ao lado puramente técnico da cultura moderna. É a trágica bifurcação diagnosticada pelo pensador inglês C. S. Lewis, ao retratar o desentendimento entre os humanistas e os tecnocratas da era contemporânea. O que hoje se faz aqui, é restituir a designação que a Grécia antiga na sua sabedoria imperecível dava à palavra "técnica", *techne* em grego, no tempo de Péricles e Aristóteles, de Platão e de Sócrates, do Partenon e de Homero, *techne* era ao mesmo tempo arte e técnica. *Techne* era o artesanato das ânforas da Macedônia e os frisos do Partenon, era a estátua de Fídias e um teorema de Euclides, um diálogo de Platão e uma ode de Safo, porque *techne* designava essencialmente o exercício de uma atividade que mudava o conceito que o homem pudesse ter da realidade. Fosse essa mudança através de uma nova perspectiva da condição do homem trazido pela Filosofia, fosse pela alteração da paisagem de Atenas como soerguimento do Partenon.

Não sei de nenhuma iniciativa semelhante do Plano da Administração Democrática de um país ou de um Estado a não ser o exemplo, tragicamente mutilado pela morte do Presidente Kennedy, dos Estados Unidos. Só o seu incentivo à intelectualidade, aos professores de Harvard e aos poetas Robert Frost e Robert Lowell, aos músicos e aos escritores precede, em tempos modernos, a iniciativa do Governador Pimentel que agora, comovidamente e cheios de gratidão, nós celebramos aqui esta tarde. Só os cegos ou os que desejamos o *status quo* por ignorância ou por interesse espúrio poderão criticar a doação de 25 milhões de cruzeiros novos de um Estado, que não é milionário, à literatura nacional. Mas os que criticarem esse arrojo -- não tenhamos dúvida -- são os mesmos que não confessam publicamente sua desaprovação da mudança social do Brasil. Detrás de cada inimigo da cultura está pelo menos em potencial um sugador dos frutos do labor do povo; cada frase obscurantista lançada contra o prestígio à literatura que este concurso traz auspiciosamente oculta um desejo talvez inconfessado, talvez inconsciente, de manter o Brasil dividido na moderna casa grande e senzala que adquiriu proporções nacionais e que assume a forma do edifício moderno e da favela, das residências confortáveis e da maloca paulista ou do mocambo pernambucano. Porque no campo da arte, da literatura, do pensamento, a lei inflexível que vigora é a mesma que preside à saúde dos povos e ao progresso social de uma nação: o combate ao *status quo*, ao marasmo, ao deixa-como-está.

Pela exemplar obra social a que Vossa Excelência prestou sua adesão esclarecida e decisiva, ao apoiar o proletariado intelectual brasileiro, ao apoiar os que têm suas oficinas imateriais dedicadas a forjar um sonho que norteia todos os ideais do homem, a criação de uma sociedade livre, democrática, socialmente justa e respeitadora da carta de direitos humanos da ONU, que inclui também além do direito ao pão o direito à vida do espírito, à educação e à liberdade de qualquer opressão econômica ou mental.

Inaugurando uma relação absolutamente nova entre o literato e o Estado, isto é, subvencionando a literatura, mas sem impor-lhe nem o critério do lucro, nem o critério do conformismo político, Vossa Excelência já responde cabalmente a qualquer crítica e já institui um exemplo para os Estados privilegiados pela riqueza e pela cultura sedimentada, como São Paulo e a Guanabara, Minas Gerais e o Rio Grande do Sul.

Em nome dos talentos que este congresso congrega, em nome dos jovens de idade e de espírito, isto é, em nome de todos os que creem em um Brasil melhor e colaboram à sua maneira para a sua rápida concretização, nós lhe asseguramos que agora estamos mais perto da nossa emancipação e da substituição de importações culturais.

Conscientes da sua cooperação decisiva e da largueza de sua visão, eu, em nome de todos os que estão aqui presentes, e espero também em nome dos que aqui se congregam, saúdo comovidamente e lhe transmito, Senhor Governador, um entusiasta muito obrigado.


