---
author: "Fernando Rey Puente"
published: true
template-partials:
  - _extensions/lgr/empty/title-block.html
  - _extensions/lgr/empty/title-metadata.html
---

::: {.content-hidden when-format="html"}

# {{< meta cover.title >}} {.unnumbered}

:::

Reuni neste volume artigos de LGR sobre os principais contistas brasileiros que não foram abordados em um volume à parte, como é o caso de Guimarães Rosa, Clarice Lispector e Hilda Hilst.

LGR diferentemente de um pesquisador meramente acadêmico da literatura brasileira estava muito atento às publicações mais recentes de diversos autores no âmbito nacional e foi um dos incentivadores do primeiro concurso nacional de contos, ocorrido em Curitiba em 1967, o que evidencia o seu engajamento político no intuito de divulgar a literatura reivindicando melhores condições para a sobrevivência dos autores e denunciar os abusos editoriais e as falhas governamentais em disponibilizar auxílios eficazes e fundamentais para a consolidação da literatura em nosso país. Ao longo de toda a sua vida professional LGR escreveu inúmeras cartas abertas para diversas autoridades públicas (de presidentes e ministros da cultura até governadores ou prefeitos) pleiteando a defesa da cultura, do livro, de um controle mais eficaz da qualidade das traduções e de uma remuneração mais justa do trabalho do tradutor.

O primeiro concurso nacional de contos consagrará Dalton Trevisan como o grande vencedor e ele será um dos autores sobre o qual nosso crítico mais abundantemente escreverá. Além dele diversos artigos de LGR se aprofundarão sobre João Antônio, J. J. Veiga, Rubem Fonseca e Otto Lara Resende, bem como sobre quatro outros na época jovens autores: Ricardo Ramos, Luiz Vilela, João Gilberto Noll e Guilherme Scalzilli. Todos eles contistas muito importantes que vieram trazer novas contribuições a um gênero extremamente bem representado em nível internacional de nossa produção literária nacional.

Acreditamos que por meio desses artigos é possível se formar uma ideia bastante fidedigna da importância de LGR na descoberta e no reconhecimento de novos autores (neste caso, de novos contistas) que foram pouco a pouco se inserindo na corrente dos grandes contistas que compõem a nossa literatura nacional, bem como, é óbvio na obra desses artistas.

Iniciamos este livro com dois artigos que nosso crítico escreveu sobre antologias de contos e que dão uma ideia muito boa de como ele avaliava diversos contistas brasileiros e como ele concebia a liberdade literária como essencial para a constituição de uma literatura genuína que não deveria estar cerceada por nenhum tipo de dogma. Em seguida, ainda nesse capítulo introdutório, inseri uma bela resenha sobre uma antologia de contos brasileiros sobre bichos e, por fim, a nota que LGR escreveu mais tardiamente chamando a atenção de suas leitoras e de seus leitores para a reedição da importante obra de Luís da Câmara Cascudo *Contos Tradicionais do Brasil*.



{{< include _extensions/lgr/_mainmatter.qmd >}}
