---
title: |
  Leo Gilson Ribeiro
view_url: https://leogilsonribeiro.com.br
---

> Que é mesmo para valer, já o título o diz. Mas vale por grata madrugada este livro de ensaios, e consola bem à gente haver um Leo Gilson.
> Ágil nos cimos raros ou nos obscuros fundos, ele me parece um gato – de lucidez e agudez. Espreita só o vivo, o que nos textos e autores verdadeiramente se mexe. Desdeixa de caroços e bagaços. Pega, capta, mede, pesa.
> E nele sente-se um mestre do entendimento, já se libertando na Caverna – consoante o mito platônico. Toma os símbolos pelo que devem ser: sombras reveladoras, janelas de plena transparência. Não tem medo de ver, de pensar, de olhar para cima.
> Rio adiante, assim é que – como numa das margens “de seu púlpito de nuvens”, Sören Kierkegaard, e, na outra, Novalis, o “idealista mágico” – ele nos descreve, entre mais três ou dois, menores, Kafka, tonto de crer e querer o inatingível e a milenaríssima sabedoria de Ionesco.
> Sou-lhe reconhecido pelo que nos traz: uma informação sob nítida luz e uma interpretação sempre redimidora.

-- Ass. **Guimarães Rosa** – Rio, 4 de julho de 1964.
In: Orelha do livro *Cronistas do Absurdo. Kafka, Büchner, Brecht, Ionesco.*



---

### Outubro de 2023

- Confira os novos volumes em PDF!



::: {.content-visible when-format="html"}

::: {#fig-pdfvol1 .column-page-right}

:::: {#fig-pdfvol1a}
<iframe width="25%" height="300" src="https://raw.githubusercontent.com/LeoGilsonRibeiro/leogilsonribeiro.github.io/main/_pdf/Volume-1.pdf"></iframe>
<iframe width="25%" height="300" src="https://raw.githubusercontent.com/LeoGilsonRibeiro/leogilsonribeiro.github.io/main/_pdf/Volume-2.pdf"></iframe>
:::::

Volumes 1-2 da Coleção.
:::::

:::
