---
author: "Fernando Rey Puente"
template-partials:
  - _extensions/lgr/empty/title-block.html
---

::: {.content-hidden when-format="html"}

# {{< meta cover.title >}} {.unnumbered}

:::

Nosso intuito com essa antologia de resenhas, artigos, entrevistas e ensaios de Leo Gilson Ribeiro sobre diversas/os poetas brasileiros é o de evidenciar como o crítico literário ao longo de sua longa e produtiva carreira em importantes jornais e revistas de nosso país analisou, valorizou e procurou difundir a produção poética nacional a partir de meados dos anos 60 do século passado.

Duas ausências são notórias nesta recolha: Mário de Andrade e Hilda Hilst. A justificativa para isso é que ambos esses poetas serão abordados em publicações à parte. Textos sobre a quase totalidade da produção de Hilda Hilst (inclusive das suas poesias) serão publicados juntamente com os estudos sobre Guimarães Rosa e Clarice Lispector em um livro específico e um longo ensaio sobre Mário de Andrade, escrito por ocasião de um curso sobre o movimento modernista de 1922 que nosso crítico ministrou em diversas unidades do Sesc no Estado de São Paulo (capital e interior) no ano de 1992 será publicado em um volume especial dedicado à algumas figuras representativas da Semana de Arte Moderna de 1922 de São Paulo.

Evidentemente, como a produção de Leo Gilson Ribeiro dependia de publicações de novos livros, de republicações ou de datas comemorativas (do nascimento ou morte de um escritor ou uma escritora ou de celebração de um evento editorial importante), os textos aqui reunidos apresentam um olhar atento e arguto para a produção poética no Brasil da segunda metade do século XX com a finalidade, como sempre, de levar o grande púbico que o seguia em jornais e revistas da época a se aproximar dessas e desses autores sobre os quais escreveu sempre com muito rigor e profissionalismo, mas em uma linguagem escorreita e clara.

Ainda na coluna "Janelas Abertas" por ele criada na revista *Caros Amigos*, último veículo de imprensa no qual contribuiu assiduamente, Leo Gilson Ribeiro estava sempre atento às novas publicações de poesia no Brasil. Assim, na edição de junho de 1998 ele vê o surgimento do livro *Estas Muitas Minas* de Ângela Leite de Souza como uma "agradável surpresa" por apresentar "uma genuína voz poética nova" no Brasil. Como ele, sucinta mas eloquentemente a define, a poetisa é, em suas palavras, "uma das mais importantes e marcantes novas presenças poéticas neste país à míngua de talentos profundos como as minas que brotam do lirismo mágico dessa poetisa estreante e já triunfante". Na edição de fevereiro de 1999 da *Caros Amigos* é a vez de ele saudar a edição da obra reunida de Olga Savary, *Repertório Selvagem*, que ele sintetiza em um curto parágrafo: "São doze livros de poesia com a delicadeza de uma aquarela oriental, a melancolia de uma peça de piano de Chopin e a cultura sempre oculta por modéstia mas arquitrave de sua esplêndida criação poética muitos anos a fio. Como sempre, por perto o mar, a abstração do corpo carnudo, uma presença que quase sempre passa, lépida, diáfana, como forma apenas de despedir". Olga Savary é para Leo Gilson Ribeiro, como ele afirma, juntamente com Marly de Oliveira, "uma das mais discretas grandes poetas da literatura contemporânea". Na edição de abril de 2001, é a vez de uma voz poética gaúcha aparecer nas "Janelas Abertas": Maria Carpi. Por ocasião da publicação de seu livro *A migalha e a fome* e de outros mais que a autora escreveu o crítico comenta: "toca-se o deslumbramento nesses livros que são uma epifania e a colocam entre os mais altos postos como poeta brasileira contemporânea". Por fim, mas de modo algum em último lugar, caberia mencionar as várias breves menções a Manoel de Barros na *Caros Amigos*, mas fiquemos apenas com a última delas (da edição de fevereiro de 2006) na qual Leo Gilson Ribeiro assim se refere ao livro *Poemas Rupestres*: "É imprescindível que nós, sem recursos, nos abriguemos na poesia e hoje em dia a língua portuguesa no Brasil é arrebatadora, inigualável, por exemplo, em nosso Eliot do pequeno mundo rural de Mato Grosso e do Pantanal, Manoel de Barros, sempre alegre e diferente de qualquer poeta contemporâneo. Quem, como absoluto primo de Lewis Carrol da Inglaterra vitoriana, poderia deixar essa visão deslumbrante - sem *nonsense* nem sonho, é apenas o Homem, como diz Manoel de Barros, desenhando pinturas rupestres e terminando com a poesia antiga."

Esperemos que todo esse material aqui reunido sirva como uma prova inconteste da importância do trabalho crítico de Leo Gilson Ribeiro como leitor atento e abalizado de poetas brasileiros durante toda a segunda metade do século XX até a sua morte ocorrida em 2007 pouco antes de completar os 78 anos de idade. Acreditamos que a maior preocupação de nosso crítico era o de estimular a leitura da poesia brasileira dentre os mais jovens e todos aqueles que não tiveram a oportunidade de ter uma formação mais esmerada. Para além de ser lembrado apenas como um crítico literário que de certo modo descobriu e promoveu a hoje reconhecidamente genial escritora Hilda Hilst, ele deve ser recordado como alguém que realizou um trabalho minucioso de análise e juízo crítico sobre a produção da prosa e da poesia brasileiras e de outros países que não deve permanecer ignorado apenas pelo fato que ele estava fora do mundo acadêmico e que seus textos, as mais das vezes, foram circunstanciais e limitados pelos ditames rigorosas das laudas estipuladas pela imprensa. Que esta antologia de alguns de seus textos mais importantes sobre as/os poetas brasileiros contemporâneos sirva para recolocá-lo na posição que ele merece de um dos principais críticos de literatura que o Brasil já teve.


{{< include _extensions/lgr/_mainmatter.qmd >}}
