---
author: "Fernando Rey Puente"
published: true
template-partials:
  - _extensions/lgr/empty/title-block.html
  - _extensions/lgr/empty/title-metadata.html
---

::: {.content-hidden when-format="html"}

# {{< meta cover.title >}}: {{< meta cover.subtitle >}} {.unnumbered}

:::

Leo Gilson Ribeiro teve a oportunidade de escrever sobre a Semana de Arte Moderna de 1922 ao menos duas vezes, quando da comemoração respectiva dos cinquenta e sessenta anos desse evento que, como se sabe, modificou o modo dos artistas brasileiros conceberem a sua produção artística. Resolvi reunir esses dois artigos sobre a Semana de Arte Moderna de 1922 juntamente com duas importantes entrevistas que ele realizou: uma com Tarsila do Amaral e outra com Menotti del Picchia, dois dos integrantes do evento em questão. Acrescentei a esse material dois belos depoimentos de nosso crítico sobre Di Cavalcanti, de quem era amigo próximo, dado a relevância deste pintor para o movimento modernista. Reuni por fim, um artigo sobre Oswald de Andrade e dois outros sobre Mário de Andrade e principalmente um material inédito datilografado sobre um curso ministrado por Leo Gilson Ribeiro em diversas unidades do Sesc São Paulo em 1992, comemorando assim os setenta anos das célebres três noites paulistas que abalaram para sempre o modo de conceber as artes, a música e a literatura no Brasil. Espero com isso ter produzido um pequeno volume que possa ajudar os jovens de hoje a se informar e a refletir sobre alguns dos artistas envolvidos nas noitadas tão contestadas ocorridas em fevereiro de 1922 no Teatro Municipal de São Paulo.


{{< include _extensions/lgr/_mainmatter.qmd >}}
