---
author: "Fernando Rey Puente"
template-partials:
  - _extensions/lgr/empty/title-block.html
---

::: {.content-hidden when-format="html"}

# {{< meta cover.title >}}: {{< meta cover.subtitle >}} {.unnumbered}

:::

Leo Gilson Ribeiro tinha um interesse muito especial pela literatura italiana e particularmente pela literatura italiana do pós-guerra e por isso resolvemos reunir neste volume os textos que ele pôde escrever ao longo dos anos sobre alguns de seus principais representantes. Optamos por agrupar os escritores aqui enfeixados a partir de um critério cronológico (a data de nascimento de cada um deles) a fim de possibilitar ao leitor uma visão minimamente histórica desse apanhado de artigos escritos sempre por razões circunstanciais: falecimentos, visitas ao Brasil, premiações obtidas ou publicações de traduções de obras de um ou outro desses autores.

O título deste livro nós o retiramos de um artigo do próprio LGR sobre o escritor Carlo Emilio Gadda, artigo no qual nosso crítico afirma que a literatura italiana se caracteriza por ser "uma literatura sempre empenhada na perscrutação do humano". Apesar de os artigos terem sido escritos ao longo de quatro décadas e de circunstâncias diversas é possível por meio de sua leitura ter um apanhado bastante razoável de parte significativa da produção italiana do pós-guerra. Isso ocorre, pois frequentemente LGR faz minirretrospectivas de autores e de livros de autores que muitas vezes não puderam ser tratados individualmente, mas que são apresentados indiretamente em vários dos artigos aqui reunidos. Isso se deve, obviamente, ao conhecimento bastante acurado que ele possuía dessa literatura pela qual nutria muita admiração e estima. Encontramos entre seus papéis avulsos 19 páginas datilografadas com análises de diversos escritores italianos. Provavelmente são as notas do curso que ele ministrou no Instituto Italiano de Cultura no Rio de Janeiro denominado "Introdução às modernas correntes da literatura italiana" nos anos 60 do século passado. Ainda no último veículo de imprensa para o qual escreveu (a revista *Caros Amigos*) e onde mantinha uma coluna (intitulada "Janelas Abertas") menciona com muita admiração o novo romance de Italo Calvino publicado então no Brasil (*Se um Viajante numa Noite de Inverno*) chamando-o de um "origama fascinante" e de um livro "precioso" (*Caros Amigos*, n. 29, agosto de 1999), assim como no ano 2001 saúda a publicação no nosso país do *Diário Póstumo* de Eugenio Montale que ele caracterizava então como sendo "um labirinto mágico, guardando ciosamente seus mistérios profundos à imaginação criadora dos leitores" e termina sentenciando seu breve juízo dessa obra na língua de Dante que ele tanto amou e tentou prestigiar: "*Veramente magnífico*!" (*Caros Amigos*, n.49, abril de 2001).

{{< include _extensions/lgr/_mainmatter.qmd >}}
