---
author: "Fernando Rey Puente"
published: true
template-partials:
  - _extensions/lgr/empty/title-block.html
  - _extensions/lgr/empty/title-metadata.html
---

::: {.content-hidden when-format="html"}

# {{< meta cover.title >}}: {{< meta cover.subtitle >}} {.unnumbered}

:::

Sem sombra de dúvida, a paixão de Leo Gilson Ribeira pela língua inglesa era total e isso ficava evidente pelos elogios que ele sempre fazia em nossas conversas sobre "a maior estilista da língua inglesa" como ele não cansava de repetir. É uma pena que ele nunca tenha tido tempo para escrever um livro inteiro sobre Virginia Woolf ou sobre Doris Lessing, outra de suas grandes paixões literárias. Ambas, conjuntamente com a escritora de língua francesa Marguerite Yourcenar, primeira mulher a entrar na Academia Francesa de Letras, representam uma tríade de autoras muito prestigiadas por nosso crítico e que focalizaram em suas obras questões sobre a mulher para as quais nosso crítico sempre estava muito atento.

Resolvemos reunir os textos consagradas por ele a essas três autoras em um volume autônomo, como testemunho de uma espécie de tributo que ele sempre se preocupou em fazer à inteligência, sensibilidade e lucidez de diversas escritoras do Brasil e do mundo. Do mesmo modo, já havíamos reunido também os textos de Leo Gilson Ribeiro sobre Clarice Lispector e Hilda Hilst, duas escritoras com as quais ele manteve um forte vínculo de amizade, bem como, obviamente, de imensa admiração literária. Cabe mencionar também a escritora italiana Elsa Morante que nosso crítico chegou a conhecer e a entrevistar no Rio de Janeiro, mas que pela escassez desse material preferimos incluir no volume dedicado à literatura italiana a qual ele considerava ser, injustamente, a "mais subestimada do Ocidente".

O seu grande entusiasmo por essas três artistas europeias fica explícito nesses textos aqui reunidos e que foram escritos, como sempre, em função de diversas circunstâncias jornalísticas: resenhas sobre livros publicados, datas comemorativas, análises de livros ou da obra e no caso de Doris Lessing também uma entrevista. Algo que ele também havia feito com Clarice Lispector, com Hilda Hilst e com Elsa Morante, dentre as muitas outras escritoras que ele entrevistou em sua carreira.

Com relação a Doris Lessing, percebe-se também o quanto a leitura extensa e atenta de sua obra foi decisiva na ênfase sobre muitas das ideias de nosso crítico que já estavam presentes nele desde os seus primeiros textos, mas que foram se acentuando com o passar do tempo. As denúncias sobre as injustiças contra as mulheres, a dimensão ética orientando e presidindo a escrita com veementes denúncias contra os diversos tipos de racismo e contra os preconceitos étnicos, enfim, um olhar múltiplo sobre os distintos povos não ocidentais e sobre a catástrofe ecológica que já se anunciava nas décadas de 70 e 80 do século passado e para a qual Leo Gilson Ribeiro esteve sempre muito atento e para a qual sempre chamou a atenção de suas/seus leitoras/es.

{{< include _extensions/lgr/_mainmatter.qmd >}}
