format:
  lgr-pdf

project:
  type: book
  output-dir: ../_pdf/

filters:
  - fontawesome
  - lgr

book:
  chapters:
    - index.qmd
    - 01-recepcao-no-brasil/00-brasil-entre-dogpatch-e-yoknapatawpha.md
    - 01-recepcao-no-brasil/01-a-literatura-de-protesto-americana-e-as-suas-raizes-romanticas.md
    - part: "E. A. Poe (1809-1848)"
      chapters:
        - 02-e-a-poe/00-o-pai-do-medo-resenha-do-livro-historias-extraordinarias-de-e-a-poe.md
    - part: "Walt Whitman (1819-1892)"
      chapters:
        - 03-walt-whitman/00-walt-whitman-poeta-polemico.md
    - part: "Emily Dickinson (1830-1886)"
      chapters:
        - 04-emily-dickinson/00-emily-dickinson.md
    - part: "Mark Twain (1835-1910)"
      chapters:
        - 05-mark-twain/00-mark-twain-segundo-o-professor-hamlin-hill.md
        - 05-mark-twain/01-patriotas-e-traidores-mark-twain.md
    - part: "Henry James (1843-1916)"
      chapters:
        - 06-henry-james/00-a-redescoberta-de-henry-james.md
        - 06-henry-james/01-a-redescoberta-de-henry-james-ii.md
        - 06-henry-james/02-a-tragedia-e-a-vitoria-de-henry-james.md
    - part: "Ezra Pound (1855-1972)"
      chapters:
        - 07-ezra-pound/00-ezra-pound-1855-1972.md
        - 07-ezra-pound/01-ezra-pound-um-criador-hermetico-dificil-talvez-inimitavel-como-joyce.md
    - part: "Henry Miller (1891-1980)"
      chapters:
        - 08-henry-miller/00-a-nova-edicao-de-tropico-de-cancer-e-a-primeira-de-plexus.md
        - 08-henry-miller/01-a-morte-de-henry-miller-a-importancia-de-sua-obra.md
        - 08-henry-miller/02-a-literatura-e-o-mundo-de-henry-miller-uma-proibicao-a-obediencia.md
    - part: "Scott Fitzgerald (1896-1940)"
      chapters:
        - 09-scott-fitzgerald/00-fitzgerald-e-o-mito-americano.md
        - 09-scott-fitzgerald/01-scott-e-zelda-um-caso-de-amor-nos-anos-loucos.md
    - part: "John dos Passos (1896-1970)"
      chapters:
        - 10-john-dos-passos/00-dez-anos-sem-john-dos-passos-um-vazio-de-lucidez.md
    - part: "W. Faulkner (1897-1962)"
      chapters:
        - 11-william-faulkner/00-william-faulkner-e-a-exegese-do-sul.md
        - 11-william-faulkner/01-william-faulkner-o-mito-a-arte-a-etica.md
        - 11-william-faulkner/02-o-urso-um-painel-uma-tragedia-uma-outra-geografia.md
        - 11-william-faulkner/03-faulkner-o-poeta-das-velhas-verdades.md
    - part: "E. Hemingway (1899-1961)"
      chapters:
        - 12-ernest-hemingway/00-resenha-do-livro-papa-hemingway-de-a-e-hotchner.md
        - 12-ernest-hemingway/01-hemingway-o-grande-nao-passou-de-uma-lenda.md
        - 12-ernest-hemingway/02-hemingway-que-horror-resenha-do-livro-postumo-o-jardim-do-eden.md
    - part: "Nabokov (1899-1977)"
      chapters:
        - 13-nabokov/00-nabokov.md
        - 13-nabokov/01-nabokov-bufao-lucido-critico-irresistivel-e-irrepetivel.md
    - part: "Auden (1907-1963)"
      chapters:
        - 14-auden/00-auden.md
    - part: "W. Saroyan (1908-1981)"
      chapters:
        - 15-william-saroyan/00-ainda-existem-leitores-para-temas-como-os-desse-escritor-ingenuo.md
    - part: "Paul Bowles (1910-1999)"
      chapters:
        - 16-paul-bowles/00-mundos-incomunicaveis-resenha-do-livro-cha-nas-montanhas.md
    - part: "E. Bishop (1911-1979)"
      chapters:
        - 17-elizabeth-bishop/00-a-poetisa-o-caju-e-o-micucu-entrevista.md
    - part: "S. Bellow (1915-2005)"
      chapters:
        - 18-saul-bellow/00-ironia-letrada-e-brados-humanistas-entre-bocejos.md
        - 18-saul-bellow/01-um-diagnostico-do-contraste-entre-politica-e-paz-por-saul-bellow.md
        - 18-saul-bellow/02-a-saga-tragicomica-de-um-americano-nada-tranquilo.md
    - part: "J. D. Salinger (1909-2010)"
      chapters:
        - 19-j-d-salinger/00-j-d-salinger.md
    - part: "R. Bradbury (1920-2012)"
      chapters:
        - 20-ray-bradbury/00-o-terrivel-futuro-de-bradbury.md
        - 20-ray-bradbury/01-memorias-do-futuro.md
    - part: "N. Mailer (1923-2007)"
      chapters:
        - 21-norman-mailer/00-673-paginas-que-levam-a-exaustao-sem-recompensa.md
    - part: "T. Capote (1924-1984)"
      chapters:
        - 22-truman-capote/00-o-ultimo-livro-de-truman-capote.md
        - 22-truman-capote/01-capote-um-escritor-a-sangue-frio.md
        - 22-truman-capote/02-um-livro-que-consola-ate-os-quatro-quintos-da-humanidade-que-nao-comem.md
    - part: "W. Kennedy (1928)"
      chapters:
        - 23-william-kennedy/00-william-kennedy-o-humanista-entrevista.md
    - part: "P. Roth (1933-2018)"
      chapters:
        - 24-philip-roth/00-comedia-sexual-resenha-do-livro-complexo-de-portnoy.md
        - 24-philip-roth/01-a-terapia-que-rendeu-um-milhao-de-dolares.md
    - part: "Raymond Carver (1938-1988)"
      chapters:
        - 25-raymond-carver/00-o-poeta-dos-vencidos-entrevista.md
    - part: "P. Auster (1947-2024)"
      chapters:
        - 26-paul-auster/00-a-ficcao-que-nao-foi-inventada-entrevista.md
